### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by Aericio** [GMNetwork/MyPlot#1]
# ***High Priority (Causes Crashes)***

- [ ] Fix /p clear [confirm]

- [ ] Fix /p biome [biome]

# ***Low Priory (Enhancements)***

- [ ] Add a world border and allowing it to extend when a new plot on a new row is claimed. (Prevents players loading a lot of chunks by flying out)

# ***Crash Message + Debug2***

**Comment by SalmonGER** [comment]
/p clear crashes because $this->level is undefined. Will do a little workaround since I can't fix it on phone rn

**Comment by SalmonGER** [comment]
@SalmonGER actually nvm. I have a little idea but can't really look into it rn

**Comment by thebigsmileXD** [comment]
P clear never crashed for me.

**Comment by Aericio** [comment]
Why ;(
#blamesalmonsbincompiling

**Comment by Aericio** [comment]
Actually, isn't his fault. I tried with 7.0.3 bins (from PM) and it still crashed.
I am not talking about just /p clear, do /p clear confirm crashes it.

**Comment by thebigsmileXD** [comment]
https://thesilphroad.com/research#monRater

**Comment by Aericio** [comment]
100% related to Minecraft coding much wow pokemango r8er opaf

**Comment by jasonwynn10** [comment]
#2 fixed plot clearing?

**Comment by jasonwynn10** [comment]
where is the error in biome setting?

**Comment by jasonwynn10** [comment]
If you all need a version of MyPlot that works, you can just use my version of it that's based on the PC plugin. https://github.com/jasonwynn10/MyPlot

**Comment by Aericio** [comment]
I was going to delete this repo lol
